apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-3
spec:
  containers:
  -  name: ubuntu-sleeper-3
     image: ubuntu
     command: ["sleep", "5000"]
     securityContext:
      capabilities:
        add: ["SYS_TIME"]
